generate:
  remove-spaces: false
  remove-comments: true
  remove-freopen: true
  force: true
  copy: false

create:
  template:
    active: false
    encoding: UTF-8
    filename: template.cpp
  data:
    active: false
    encoding: UTF-8
    filename: data.in
  categories:
    codeforces: 
      dirname: oj/codeforces
      problem-number: 5

remove:
  recursive: false
  force: false

clean:
  recursive: true
  force: true
  patterns:
    - '*.o'
    - '*.exe'
    - '_venus_*.cpp'
